baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Hugo Toigian Example Site'
theme = "hugo-toigian"
themesDir = "../.."


[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Enable user to embed HTML snippets in Markdown content.
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    noClasses = false
    tabWidth = 4
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    ordered = true
