name: Build & Commit

on:
  push:
    branches: [ master ]
    paths:
      - 'assets/prebuild.css'
  pull_request:
    branches: [ master ]
    paths:
      - 'assets/prebuild.css'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set safe directory # https://github.com/actions/checkout/issues/760
        run: |
          set -x
          git config --global --add safe.directory $GITHUB_WORKSPACE
          git config --global --add safe.directory /github/workspace

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Nodejs
        uses: actions/setup-node@v3

      - name: Install depedencies
        run: npm install

      - name: Build TailwindCSS
        run: npm run-script build

      - name: Push changes
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'master'
          commit-message: 'Build base.css'
          force-add: 'true'
          rebase: 'true'
          email: 'kiennt2609@gmail.com'
          name: 'Kien Nguyen-Tuan'
          files: 'assets/base.css'
